name: Lint Check

on:
  push:
    branches: ["master", "xyz/main"]
  pull_request:
    branches: ["master", "xyz/main"]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.16.0"

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: corepack pnpm install --frozen-lockfile

      - name: Build all packages
        run: corepack pnpm run build

      - name: Check if code is linted
        run: |
          corepack pnpm run lint
